import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import AuthSessionProvider from "../../../components/SessionProvider";
import { auth } from "../../../auth";
import { redirect } from "next/navigation";
import "bootstrap/dist/css/bootstrap.min.css";
import { BootstrapClient } from "../bootstrap-client";
import AdminLayout from "@/../components/admin/AdminLayout";


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }: LayoutProps<"/">) {

  const session = await auth();

  if (!session) {
    redirect("/login");
  }
  return (
    <html lang="en" >
      <body>
        <AuthSessionProvider>
          <AdminLayout>{children}</AdminLayout>
        </AuthSessionProvider>
        <BootstrapClient />
      </body>
    </html>
  );
}
