import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";

import "bootstrap/dist/css/bootstrap.min.css";
import { BootstrapClient } from "../bootstrap-client";
import AdminLayout from "@/../components/admin/AdminLayout";
import AuthGuard from "../../../components/AdminGuard";


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }: LayoutProps<"/">) {

  return (
    <html lang="en" >
      <body>
        <AuthGuard>
          <AdminLayout>{children}</AdminLayout>
        </AuthGuard>
        <BootstrapClient />
      </body>
    </html>
  );
}
